routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['namespace' => 'File'], function()
{
    Route::post('files/wisiwyg_upload}',
        ['as' => 'files.wisiwyg_upload', 'uses' => 'FilesController@wisiwyg_upload']
    );

    Route::get('images/{id}/resized/{size}/{crop?}',
        ['as' => 'images.resized', 'uses' => 'ImagesController@resize']
    );

    Route::resource('images', 'ImagesController', ['except' => ['destroy']]);
    Route::resource('files', 'FilesController', ['except' => ['destroy']]);
});


Route::get('admin', function () {
    return redirect('/admin/users');
});



Route::group([ 'namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth' ], function()
{
    Route::get('/dashboard', 'DashboardController@index');

    // вот такой вот хак "группа в группе", почему-то лара5.3 перестала добавлять префикс "admin." в name рутинга
    Route::group([ 'as' => 'admin.' ], function() {
        Route::resource('users', 'UsersController', ['except' => ['show', 'destroy']]);

        Route::get('contents/create/{category_id?}', ['as' => 'admin.contents.create', 'uses' => 'ContentsController@create']);
        Route::resource('contents', 'ContentsController', ['except' => ['create']]);
    });



});


Route::get('/', 'WelcomeController@index');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use Gate;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;


class UsersController extends Controller
{
    public function index()
    {
        $users = User::all();


        return view('admin.users.index', [
            'users' => $users,
        ]);
    }

    public function create()
    {
        $user = new User();

        return view('admin.users.form', ['user' => $user]);
    }


    public function store(Request $request)
    {
        $user = new User($this->user_params($request));
        $user->email = $request->get('email');

        if ($request->has('password')) {
            $user->set_password($request->get('password'));
        }

        if (Gate::allows('toggle-admin-state')) { // давать/забирать права админа может только другой админ
            $user->is_admin = $request->get('is_admin');
        }

        if ( $user->save() ) {
            flash()->success('Пользователь создан');

            return redirect()->route('admin.users.index');

        } else {
            flash()->error('Пользователь не был создан!');
            return view('admin.users.form', ['user'   => $user]);
        }
    }


    public function edit(Request $request, $id)
    {

        $user = User::find($request->route('users'));

        return view('admin.users.form', ['user' => $user]);
    }


    public function update(Request $request, $id)
    {
        $user = User::find($request->route('users'));

        if ( Gate::allows('update-user', $user) )
        {

            $user->fill($this->user_params($request));

            if ($request->has('password')) {
                $user->set_password($request->get('password'));
            }

            if (Gate::allows('toggle-admin-state')) { // давать/забирать права админа может только другой админ
                $user->is_admin = $request->get('is_admin');
            }

            if ( $user->save() ) {
                flash()->success('Пользователь сохранен');
            } else {
                flash()->error('Сохранить пользователя не удалось');

                return view('admin.users.form', ['user'    => $user]);
            }

        } else {
            flash()->error('Нет прав для изменения этого пользователя');
        }

        return redirect()->route("admin.users.index",['id' => $user]);
    }

    public function destroy($id)
    {
        //
    }

    private function user_params($request)
    {
        return $request->user ?: [];
    }

    private function crumbs($user)
    {
        $crumbs = [
            ['title' => 'Список пользователей', 'url' => route('admin.users.index')],
        ];

        if ( $user->exists ) {
            $crumb = ['title' => "Редактривание пользователя {$user->email}", 'active' => true];
        } else {
            $crumb = ['title' => "Добавление нового пользователя", 'active' => true];
        }

        array_push($crumbs, $crumb);

        return collect($crumbs);
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
    @include('admin.partials.breadcrumbs', ['crumbs' => $crumbs])

    <div class="page-header">
        <h1>{!! $crumbs->last()['title'] !!} </h1>
    </div>

    @include('admin.users.form')
@stop

resources/views/admin/users/form.blade.php
@extends('layouts.admin')

@section('content')

    <h1>
        {!! AdminUserCrumbs::items( ['user' => $user ] )->last()['title']  !!}
    </h1>

    {!! AdminUserCrumbs::show( ['user' => $user ] ) !!}


    <div class="row">

        <div class="tab-user">
            <div id="info" class="tab-pane fade in active">

                @include('admin.partials.errors', ['errors' => $user->errors])


                <div class="row top-buffer">


                    {!! Form::resource($user, ['route' => 'admin.users', 'class' => 'form-horizontal']) !!}

                    <div class="form-group">
                        {!! Form::label('user[name]', 'Имя', ['class' => 'control-label col-sm-2'])  !!}
                        <div class="col-sm-4">
                            {!! Form::text('user[name]', $user->name, array('class' => 'form-control')) !!}
                        </div>
                    </div>

                    @unless ($user->exists)
                        <div class="form-group">
                            {!! Form::label('email', 'E-mail', ['class' => 'control-label col-sm-2'])  !!}
                            <div class="col-sm-3">
                                {!! Form::email('email', $user->email, array('class' => 'form-control')) !!}
                            </div>
                        </div>
                    @endunless


                    <div class="form-group">
                        {!! Form::label('password', 'Новый пароль', ['class' => 'control-label col-sm-2'])  !!}
                        <div class="col-sm-3">
                            {!! Form::password('password', array('class' => 'form-control')) !!}
                        </div>
                    </div>


                    @can('toggle-admin-state')
                    <div class="form-group">
                        <div class="col-sm-3 col-sm-offset-2">
                            <div class="checkbox">
                                <label>
                                    {!! Form::boolean('is_admin', $user->is_admin) !!} Админ
                                </label>
                            </div>
                        </div>
                    </div>
                    @endcan


                    {{--<div class="form-group">--}}
                    {{--{!! Form::label('pass_confirm', 'Подтвердите пароль', ['class' => 'control-label col-sm-2'])  !!}--}}
                    {{--<div class="col-sm-3">--}}
                    {{--{!! Form::password('pass_confirm', array('class' => 'form-control')) !!}--}}
                    {{--</div>--}}
                    {{--</div>--}}



                    <div class="form-group">
                        <div class="row top-buffer">
                            <div class="col-sm-8 col-md-offset-2">
                                {!! Form::submit('Сохранить', ['name' => 'action[save]', 'class' => 'btn btn-primary']) !!}

                                <div class="pull-right">

                                    {!! link_to(URL::previous(), 'Отмена', ['class' => 'btn btn-primary']) !!}

                                </div>

                            </div>
                        </div>
                    </div>

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')


@section('content')

    <div class="row">

        <h1>Пользователи
            {!! link_to_route('admin.users.create', 'Добавить', [], ['class' => 'btn btn-primary dropdown-toggle']) !!}
        </h1>

        @if ($users->isEmpty())
            <p>Нет ни одного товара</p>

        @else

            <table class="table table-hover">
                <colgroup>
                    <col width="70px"/>
                </colgroup>
                <thead>
                <tr>
                    <th>email</th>
                    <th>Имя</th>
                </tr>
                </thead>
                <tbody>

                @foreach ($users as $user)
                    <tr>

                        <td> {!! link_to_route('admin.users.edit', $user->email, ['item_id' => $user->id]) !!} </td>
                        <td> {!! $user->name !!} </td>

                    </tr>

                @endforeach

                </tbody>
            </table>

        @endif

    </div>
@stop

resources/views/admin/users/new.blade.php
@extends('layouts.admin')

@section('content')
    @include('admin.partials.breadcrumbs', ['crumbs' => $crumbs])

    <div class="page-header">
        <h1>{!! $crumbs->last()['title'] !!} </h1>
    </div>

    @include('admin.users.form')
@stop